name: Deploy CI/CD Github Action Exercise
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: pull and execute changes to VPS repo
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                    PATH="/usr/local/go/bin/:$PATH"
                    cd ~/arif/action-test
                    git fetch
                    git pull origin master
                    go build -o action-test .
                    systemctl restart arifgo
